# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory$git_branch$git_status$git_metrics$fill$time
$character
"""

add_newline = true

[fill]
symbol = ' '

[character] 
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)' 

[directory]
truncate_to_repo = true
truncation_length = 3 

[git_branch]
disabled = false
symbol = ' '

[git_status]
disabled = true

[git_metrics]
disabled = false

[nodejs]
disabled = false
format = '[$symbol($version)]($style)'

[deno]
disabled = false
format = '[$symbol($version )]($style)'

[golang]
disabled = false
format = '[$symbol($version )]($style)'

[rust]
disabled = false
format = '[$symbol($version )]($style)'

[ruby]
disabled = false
format = '[$symbol($version )]($style)'

[time]
disabled = false
format =  '[$time]($style)' 
